# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/XilinxProjects/GameOfLife/GameOfLife.srcs/sources_1/ip/blk_mem_8x180/blk_mem_8x180.xci
# IP: The module: 'blk_mem_8x180' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/XilinxProjects/GameOfLife/GameOfLife.srcs/sources_1/ip/blk_mem_8x180/blk_mem_8x180_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_8x180'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ubuntu/XilinxProjects/GameOfLife/GameOfLife.srcs/sources_1/ip/blk_mem_8x180/blk_mem_8x180.xci
# IP: The module: 'blk_mem_8x180' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/XilinxProjects/GameOfLife/GameOfLife.srcs/sources_1/ip/blk_mem_8x180/blk_mem_8x180_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_8x180'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
