#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Jul 18 20:20:53 UTC 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a508880aa4844ed08da4f4974ff1110c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot MainSim_func_synth xil_defaultlib.MainSim -log elaborate.log"
xelab -wto a508880aa4844ed08da4f4974ff1110c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot MainSim_func_synth xil_defaultlib.MainSim -log elaborate.log

