# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/XilinxProjects/GameOfLife/GameOfLife.srcs/sources_1/ip/GameOfLife/GameOfLife.xci
# IP: The module: 'GameOfLife' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/XilinxProjects/GameOfLife/GameOfLife.srcs/sources_1/ip/GameOfLife/constraints/fun_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GameOfLife'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ubuntu/XilinxProjects/GameOfLife/GameOfLife.srcs/sources_1/ip/GameOfLife/GameOfLife.xci
# IP: The module: 'GameOfLife' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/XilinxProjects/GameOfLife/GameOfLife.srcs/sources_1/ip/GameOfLife/constraints/fun_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GameOfLife'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
